services:
  pg-database:
    image: postgres:13
    environment:
      - POSTGRES_PASSWORD:root
      - POSTGRES_USER:root
      - POSTGRES_DB:ny_taxi
    ports:
      - "5432:5432"
    volumes:
      - "./ny_taxi_data:/var/lib/postgresql/data:rw"
  pg-admin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=root
    ports:
      - "8080:80"
  